### ISSUE TITLE
Pre-Trained Network

### ISSUE THREAD

**Issue by raviy0807** [PaulAlbert31/DSOS#1]
Is it possible to share the trained model file?

**Comment by PaulAlbert31** [comment]
Hello Ravi, thanks for your interest in the work. What dataset are you referring to ?

**Comment by raviy0807** [comment]
Hey @PaulAlbert31 ,

I am looking for the trained model on webvision and imagenet.

**Comment by PaulAlbert31** [comment]
Hey Ravi, I just updated the repository with a link to a gdrive folder containing the trained weights

**Comment by raviy0807** [comment]
Really Appreciate!
