### ISSUE TITLE
clothing1m dataloader

### ISSUE THREAD

**Issue by summerhuang2014** [PaulAlbert31/DSOS#2]
Hi, I am very interested in your work. May I ask if you could provide the dataloader for dataset clothing1m please? thank you!

**Comment by PaulAlbert31** [comment]
Hello, thank you for your interest in our work.
I just updated the code to include the clothing1M experiments. 
The last line in the train.sh file is the command to reproduce the results

**Comment by summerhuang2014** [comment]
thank you very much!
